---
name: Games-Bingo
version: 0.14
author:
  - 'Jonas B. Nielsen, <jonasbn@cpan.org>'
abstract: a bingo game Perl implementation
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Data::Dumper: 0
  POSIX: 0
  Test::Harness: 0
  Test::More: 0
  Test::Pod: 0.95
  UNIVERSAL: 0
provides:
  Games::Bingo:
    file: lib/Games/Bingo.pm
    version: 0.14
  Games::Bingo::Card:
    file: lib/Games/Bingo/Card.pm
    version: 0.02
  Games::Bingo::Column:
    file: lib/Games/Bingo/Column.pm
    version: 0.02
  Games::Bingo::ColumnCollection:
    file: lib/Games/Bingo/ColumnCollection.pm
    version: 0.02
  Games::Bingo::Constants:
    file: lib/Games/Bingo/Constants.pm
    version: 0.01
no_index:
  directory:
    - t
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
