#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Games-Bingo
version:      0.10
version_from: lib/Games/Bingo.pm
installdirs:  site
requires:
    Test::Harness:                 0
    Test::Pod:                     0.95
    POSIX:                         0
    Data::Dumper:                  0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
